### ISSUE TITLE
unbunt 18.04  Ccache is empty.

### ISSUE THREAD

**Issue by cps-future** [ccache/ccache.github.io#3]
![1608533299403927687470038900954](https://user-images.githubusercontent.com/69693620/102747659-985aa000-439b-11eb-8c60-dfacb7934f58.jpg)
![1608533336686255466703353641178](https://user-images.githubusercontent.com/69693620/102747705-af00f700-439b-11eb-87df-f4762d76cadd.jpg)
![16085333777861110274007856965399](https://user-images.githubusercontent.com/69693620/102747755-c6d87b00-439b-11eb-9658-682580d2af9a.jpg)
I felt ccache configuration when I compiled the Android code but it didn't work. Ccache is empty.

**Comment by jrosdahl** [comment]
Hi,

This repository contains ccache's web site, so this is not the right place for support questions. See https://github.com/ccache/ccache/blob/master/CONTRIBUTING.md#asking-a-question.
