### ISSUE TITLE
when will you support HIPCC compiler？

### ISSUE THREAD

**Issue by risemeup1** [ccache/ccache.github.io#7]
I hope that ccache can develop a compilation cache specifically for the HIPCC compiler.

**Comment by jrosdahl** [comment]
Hi! There are no plans to add support for HIPCC. The development of Ccache is mainly driven by the interest of individuals in the community, so contributions of such support would be welcome unless they are too intrusive or complex.

Meta note: This issue tracker is about the content of the Ccache web site, not for questions about Ccache itself. I suggest using the [Ccache discussions](https://github.com/ccache/ccache/discussions) forum for questions like this.
